# https://golangci-lint.run/usage/linters/
linters:
  enable-all: true
  disable:
    - exhaustruct # pointless
    - err113 # no need to wrap all errors, too much work
    - depguard # breaking things: https://github.com/atc0005/go-ci/issues/1024
    - gochecknoglobals # globals are sometimes ok
    - exportloopref # irrelevant since Go 1.23
    - wrapcheck # no need to wrap all errors, too much work
    - varnamelen # some short var names are actually ok
    - mnd # magic numbers are sometimes ok
    - nonamedreturns # named returns are sometimes ok

linters-settings:
  gci:
    sections:
      - standard
      - default
      - localmodule
  goconst:
    min-occurrences: 5
    ignore-tests: true

issues:
  exclude-dirs:
    - proto/
